FROM node:20.9-alpine3.18 as base

FROM base AS deps
WORKDIR /home/node/app
COPY package*.json .
RUN npm ci


FROM base AS builder
WORKDIR /home/node/app
COPY . .
COPY --from=deps /home/node/app/node_modules node_modules
RUN ./node_modules/.bin/ng build


FROM unit:1.31.1-minimal
WORKDIR /www/
# COPY --from=deps /home/node/app/node_modules node_modules
COPY --from=builder /home/node/app/dist/pet-paradise/ . 

