FROM node:20.9-alpine3.18 as base

FROM base AS deps
WORKDIR /home/node/app
COPY package*.json .
RUN npm ci


FROM base AS builder
WORKDIR /home/node/app
COPY . .
COPY --from=deps /home/node/app/node_modules node_modules
RUN ./node_modules/.bin/ng build


FROM nginx:1.25-alpine3.18
COPY --from=builder --chown=ngnix /home/node/app/dist/pet-paradise/ /home/pet-paradise/
COPY utils/nginx/pet-paradise-store.conf /etc/nginx/conf.d/default.conf

