version: "1.0"

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: pet-paradise-dirty/client
    volumes:
      - ./utils/unit/configuration.json:/www/config.json
    ports:
      - 80:80
      - 8080:8080

